version: '3'

services:
  db:
    image: postgres
  api:
    build: ./api
    command: bash -c "python manage.py runserver 0.0.0.0:80"
    volumes:
      - ./api:/app/api
      - ./frontend:/app/frontend
    ports:
      - "80:80"
    stdin_open: true
    tty: true
  frontend:
    build: ./frontend
    command: "bash -c 'npm install && npm run watch'"
    volumes:
      - ./frontend:/app/frontend
    stdin_open: true
    tty: true
