version: '3'

services:
  db:
    image: postgres
  api:
    env_file:
      - ./api/prod.env
    build:
      context: ./api
      dockerfile: prod.Dockerfile
    command: bash -c 'gunicorn config.wsgi:application --bind 0.0.0.0:8000'
    volumes:
      - ./api:/app/api
      - ./frontend:/app/frontend
      - ./empotech:/app/empotech
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
  frontend:
    build: ./frontend
    command: bash -c 'npm install && npm run watch'
    volumes:
      - ./frontend:/app/frontend
    stdin_open: true
    tty: true
  empotech:
    build: ./empotech
    command: "bash -c 'npm install && npm run watch'"
    volumes:
      - ./empotech:/app/empotech
    stdin_open: true
    tty: true
