version: '3'

services:
  db:
    image: postgres
  api:
    build:
      context: ./api
      dockerfile: prod.Dockerfile
    command: bash -c 'pip install -r prod.requirements.txt && gunicorn config.wsgi:application --bind 0.0.0.0:8000'
    volumes:
      - ./api:/app/api
      - ./frontend:/app/frontend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
  frontend:
    build: ./frontend
    command: "bash -c 'npm install && npm run watch'"
    volumes:
      - ./frontend:/app/frontend
    stdin_open: true
    tty: true
  nginx:
    image: nginx
    volumes:
      - ./frontend:/app/frontend
      - ./nginx/nginx:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot

    ports:
      - 80:80
      - 443:443
    stdin_open: true
    tty: true
  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
